In [1]:
%cd ..
%pwd

/workspace/DeepSpeech-2.x


'/workspace/DeepSpeech-2.x'

In [2]:
import numpy as np
import paddle
from yacs.config import CfgNode as CN

from deepspeech.models.u2 import U2Model
from deepspeech.utils.layer_tools import print_params
from deepspeech.utils.layer_tools import summary

/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
[WARNING 2021/04/16 10:35:27 __init__.py:93] register user softmax to paddle, remove this when fixed!
[WARNING 2021/04/16 10:35:27 __init__.py:97] register user log_softmax to paddle, remove this when fixed!
[WARNING 2021/04/16 10:35:27 __init__.py:101] register user sigmoid to paddle, remove this when fixed!
[WARNING 2021/04/16 10:35:27 __init__.py:105] 

In [3]:
conf_str='examples/aishell/s1/conf/conformer.yaml'
cfg = CN().load_cfg(open(conf_str))
cfg.model.input_dim = 80
cfg.model.output_dim = 4233
cfg.model.cmvn_file = "/workspace/wenet/examples/aishell/s0/raw_wav/train/global_cmvn"
cfg.model.cmvn_file_type = 'json'
cfg.freeze()

model = U2Model(cfg.model)
print_params(model)


/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
[INFO 2021/04/16 10:35:28 u2.py:834] U2 Encoder type: conformer
[INFO 2021/04/16 10:35:28 u2.py:834] U2 Encoder type: conformer


encoder.embed.conv.0.weight | [256, 1, 3, 3] | 2304 | True
encoder.embed.conv.0.bias | [256] | 256 | True
encoder.embed.conv.2.weight | [256, 256, 3, 3] | 589824 | True
encoder.embed.conv.2.bias | [256] | 256 | True
encoder.embed.linear.weight | [4864, 256] | 1245184 | True
encoder.embed.linear.bias | [256] | 256 | True
encoder.after_norm.weight | [256] | 256 | True
encoder.after_norm.bias | [256] | 256 | True
encoder.encoders.0.self_attn.pos_bias_u | [4, 64] | 256 | True
encoder.encoders.0.self_attn.pos_bias_v | [4, 64] | 256 | True
encoder.encoders.0.self_attn.linear_q.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_q.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_k.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_k.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_v.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_v.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_out.weight | 

In [4]:
summary(model)

encoder.global_cmvn.mean | [80] | 80
encoder.global_cmvn.istd | [80] | 80
encoder.embed.conv.0.weight | [256, 1, 3, 3] | 2304
encoder.embed.conv.0.bias | [256] | 256
encoder.embed.conv.2.weight | [256, 256, 3, 3] | 589824
encoder.embed.conv.2.bias | [256] | 256
encoder.embed.linear.weight | [4864, 256] | 1245184
encoder.embed.linear.bias | [256] | 256
encoder.after_norm.weight | [256] | 256
encoder.after_norm.bias | [256] | 256
encoder.encoders.0.self_attn.pos_bias_u | [4, 64] | 256
encoder.encoders.0.self_attn.pos_bias_v | [4, 64] | 256
encoder.encoders.0.self_attn.linear_q.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_q.bias | [256] | 256
encoder.encoders.0.self_attn.linear_k.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_k.bias | [256] | 256
encoder.encoders.0.self_attn.linear_v.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_v.bias | [256] | 256
encoder.encoders.0.self_attn.linear_out.weight | [256, 256] | 65536
encoder.encoders.0.

decoder.decoders.3.src_attn.linear_q.bias | [256] | 256
decoder.decoders.3.src_attn.linear_k.weight | [256, 256] | 65536
decoder.decoders.3.src_attn.linear_k.bias | [256] | 256
decoder.decoders.3.src_attn.linear_v.weight | [256, 256] | 65536
decoder.decoders.3.src_attn.linear_v.bias | [256] | 256
decoder.decoders.3.src_attn.linear_out.weight | [256, 256] | 65536
decoder.decoders.3.src_attn.linear_out.bias | [256] | 256
decoder.decoders.3.feed_forward.w_1.weight | [256, 2048] | 524288
decoder.decoders.3.feed_forward.w_1.bias | [2048] | 2048
decoder.decoders.3.feed_forward.w_2.weight | [2048, 256] | 524288
decoder.decoders.3.feed_forward.w_2.bias | [256] | 256
decoder.decoders.3.norm1.weight | [256] | 256
decoder.decoders.3.norm1.bias | [256] | 256
decoder.decoders.3.norm2.weight | [256] | 256
decoder.decoders.3.norm2.bias | [256] | 256
decoder.decoders.3.norm3.weight | [256] | 256
decoder.decoders.3.norm3.bias | [256] | 256
decoder.decoders.3.concat_linear1.weight | [512, 256] | 131072


In [5]:
%ls .notebook

dataloader.ipynb                       mask_and_masked_fill_test.ipynb
dataloader_with_tokens_tokenids.ipynb  model.npz
data.npz                               python_test.ipynb
encoder.npz                            train_test.ipynb
hack_api_test.ipynb                    u2_model.ipynb
jit_infer.ipynb


In [6]:
data = np.load('.notebook/data.npz', allow_pickle=True)
keys=data['keys']
feat=data['feat']
feat_len=data['feat_len']
text=data['text']
text_len=data['text_len']

In [7]:
print(keys)
print(feat.shape)
print(feat)
print(feat_len)
print(text)
print(text_len)

['BAC009S0739W0246' 'BAC009S0727W0424' 'BAC009S0753W0412'
 'BAC009S0756W0206' 'BAC009S0740W0414' 'BAC009S0728W0426'
 'BAC009S0739W0214' 'BAC009S0753W0423' 'BAC009S0734W0201'
 'BAC009S0740W0427' 'BAC009S0730W0423' 'BAC009S0728W0367'
 'BAC009S0730W0418' 'BAC009S0727W0157' 'BAC009S0749W0409'
 'BAC009S0727W0418']
(16, 207, 80)
[[[ 8.994624   9.538309   9.191589  ... 10.507416   9.563305   8.256403 ]
  [ 9.798841  10.405224   9.26511   ... 10.251211   9.543982   8.873768 ]
  [10.6890745 10.395469   8.053548  ...  9.906749  10.064903   8.050915 ]
  ...
  [ 9.217986   9.65069    8.505259  ...  9.687183   8.742463   7.9865475]
  [10.129122   9.935194   9.37982   ...  9.563894   9.825992   8.979543 ]
  [ 9.095531   7.1338377  9.468001  ...  9.472748   9.021235   7.447914 ]]

 [[11.430976  10.671858   6.0841026 ...  9.382682   8.729745   7.5315614]
  [ 9.731717   7.8104815  7.5714607 ... 10.043035   9.243595   7.3540792]
  [10.65017   10.600604   8.467784  ...  9.281448   9.186885   8.070343 ]
 

In [8]:
# ['BAC009S0739W0246', 'BAC009S0727W0424', 'BAC009S0753W0412', 'BAC009S0756W0206', 'BAC009S0740W0414', 'BAC009S0728W0426', 'BAC009S0739W0214', 'BAC009S0753W0423', 'BAC009S0734W0201', 'BAC009S0740W0427', 'BAC009S0730W0423', 'BAC009S0728W0367', 'BAC009S0730W0418', 'BAC009S0727W0157', 'BAC009S0749W0409', 'BAC009S0727W0418']
# torch.Size([16, 207, 80])
# tensor([[[ 8.9935,  9.5377,  9.1939,  ..., 10.4592,  9.5223,  8.2839],
#          [ 9.7994, 10.4060,  9.2669,  ..., 10.2340,  9.5668,  8.7706],
#          [10.6888, 10.3949,  8.0560,  ...,  9.9335, 10.1175,  8.1560],
#          ...,
#          [ 9.2174,  9.6504,  8.5052,  ...,  9.6707,  8.7834,  8.0564],
#          [10.1287,  9.9347,  9.3788,  ...,  9.5698,  9.8277,  8.9262],
#          [ 9.0959,  7.1305,  9.4666,  ...,  9.5228,  8.9921,  7.4808]],

#         [[11.4309, 10.6716,  6.0973,  ...,  9.3820,  8.7208,  7.6153],
#          [ 9.7314,  7.8097,  7.5711,  ..., 10.0005,  9.2962,  7.5479],
#          [10.6502, 10.6007,  8.4671,  ...,  9.2416,  9.2412,  8.1083],
#          ...,
#          [ 9.0977,  9.2650,  8.0763,  ...,  8.3842,  8.4285,  8.0505],
#          [10.4615, 10.1473,  6.7677,  ...,  9.8455,  9.6548,  8.2006],
#          [ 7.7949,  5.6219,  7.9746,  ...,  9.9617,  9.8019,  8.0486]],

#         [[ 7.3481,  7.8987,  7.5786,  ..., 11.6611, 10.4626,  9.0665],
#          [ 8.6274,  8.4604,  7.4981,  ..., 12.4233, 11.0101,  8.9767],
#          [ 9.8315, 10.2812,  8.9717,  ..., 12.1325, 10.4014,  9.0196],
#          ...,
#          [ 7.0872,  7.4009,  6.8090,  ...,  9.3759,  9.2273,  8.1752],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         ...,

#         [[10.9333, 10.4647,  7.7200,  ..., 10.3486,  9.2818,  7.2852],
#          [10.4503,  9.9080,  9.0299,  ...,  9.9633,  9.4876,  7.6330],
#          [10.4877,  9.8130,  9.8961,  ...,  9.6017,  9.3175,  7.6303],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         [[ 9.9448,  9.5868,  8.2200,  ..., 11.6113, 11.0576,  8.7598],
#          [ 7.6800,  8.3231,  7.5294,  ..., 11.0965, 10.5442,  9.3556],
#          [ 8.6248,  9.6746,  9.8406,  ..., 11.4058, 10.9484,  8.9749],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         [[ 8.1097,  7.7619,  6.7079,  ..., 12.6548, 11.4666, 11.0747],
#          [11.3805, 11.2223,  8.6587,  ..., 12.7926, 12.2433, 11.7217],
#          [10.6778,  9.9210,  8.0447,  ..., 13.5741, 12.5711, 11.1356],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]])
# tensor([207, 207, 205, 205, 203, 203, 198, 197, 195, 188, 186, 186, 185, 180,
#         166, 163], dtype=torch.int32)
# tensor([[2995, 3116, 1209,  565,   -1,   -1],
#         [ 236, 1176,  331,   66, 3925, 4077],
#         [2693,  524,  234, 1145,  366,   -1],
#         [3875, 4211, 3062,  700,   -1,   -1],
#         [ 272,  987, 1134,  494, 2959,   -1],
#         [1936, 3715,  120, 2553, 2695, 2710],
#         [  25, 1149, 3930,   -1,   -1,   -1],
#         [1753, 1778, 1237,  482, 3925,  110],
#         [3703,    2,  565, 3827,   -1,   -1],
#         [1150, 2734,   10, 2478, 3490,   -1],
#         [ 426,  811,   95,  489,  144,   -1],
#         [2313, 2006,  489,  975,   -1,   -1],
#         [3702, 3414,  205, 1488, 2966, 1347],
#         [  70, 1741,  702, 1666,   -1,   -1],
#         [ 703, 1778, 1030,  849,   -1,   -1],
#         [ 814, 1674,  115, 3827,   -1,   -1]], dtype=torch.int32)
# tensor([4, 6, 5, 4, 5, 6, 3, 6, 4, 5, 5, 4, 6, 4, 4, 4], dtype=torch.int32)

In [9]:
!ls .notebook
data = np.load('.notebook/model.npz', allow_pickle=True)
state_dict = data['state'].item()

for key, _ in model.state_dict().items():
    if key not in state_dict:
        print(f"{key} not find.")

model.set_state_dict(state_dict)

now_state_dict = model.state_dict()
for key, value in now_state_dict.items():
    if not np.allclose(value.numpy(), state_dict[key]):
        print(key)

dataloader.ipynb		       mask_and_masked_fill_test.ipynb
dataloader_with_tokens_tokenids.ipynb  model.npz
data.npz			       python_test.ipynb
encoder.npz			       train_test.ipynb
hack_api_test.ipynb		       u2_model.ipynb
jit_infer.ipynb


In [10]:
import paddle
feat=paddle.to_tensor(feat)
feat_len=paddle.to_tensor(feat_len, dtype='int64')
text=paddle.to_tensor(text)
text_len=paddle.to_tensor(text_len, dtype='int64')

model.eval()
total_loss, attention_loss, ctc_loss = model(feat, feat_len,
                                         text, text_len)
print(total_loss, attention_loss, ctc_loss )

/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:686: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:


Tensor(shape=[16, 51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[-0.98870903, -0.07539634,  0.03839889, ...,  0.28173494,  0.36495337, -0.03607073],
         [-0.36884263, -0.22921059, -0.09850989, ...,  1.17554832,  0.49281687,  1.22981191],
         [-0.42831492,  0.14306782, -0.40504572, ...,  1.19258320,  0.28560629,  0.84126252],
         ...,
         [-1.14067113, -0.90225518,  0.08112312, ...,  0.22529972,  0.98848087,  1.42083788],
         [-1.34911966,  0.18967032,  0.27775878, ...,  0.31862095,  0.63177413,  0.15082565],
         [-0.95137477, -0.03690310, -0.21094164, ...,  0.99404806,  0.53174424,  1.83114266]],

        [[-0.40670884,  0.22098994, -0.52978617, ..., -0.16111313,  0.73881495,  0.01380203],
         [-0.51442140, -0.45173034, -0.45147005, ...,  1.22010005,  1.24763870,  0.03303454],
         [-0.65140647,  0.16316377, -0.43823493, ...,  1.64499593,  0.57617754,  0.28116497],
         ...,
         [-0.53139108, -0.20081151,  0.5

In [11]:
# tensor(142.4635, grad_fn=<AddBackward0>) tensor(41.8416, grad_fn=<DivBackward0>) tensor(377.2479, grad_fn=<DivBackward0>)

In [12]:
encoder_out, encoder_mask = model.encoder(feat, feat_len)
print(encoder_out.shape)
print(encoder_mask.shape)
print(encoder_out[0])


[16, 51, 256]
[16, 1, 51]
Tensor(shape=[51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[-0.98870903, -0.07539634,  0.03839889, ...,  0.28173494,  0.36495337, -0.03607073],
        [-0.36884263, -0.22921059, -0.09850989, ...,  1.17554832,  0.49281687,  1.22981191],
        [-0.42831492,  0.14306782, -0.40504572, ...,  1.19258320,  0.28560629,  0.84126252],
        ...,
        [-1.14067113, -0.90225518,  0.08112312, ...,  0.22529972,  0.98848087,  1.42083788],
        [-1.34911966,  0.18967032,  0.27775878, ...,  0.31862095,  0.63177413,  0.15082565],
        [-0.95137477, -0.03690310, -0.21094164, ...,  0.99404806,  0.53174424,  1.83114266]])


In [13]:
!ls
data = np.load('.notebook/encoder.npz', allow_pickle=True)
torch_mask = data['mask']
torch_encoder_out = data['out']

deepspeech  examples  README_cn.md	setup.sh     tools
docs	    LICENSE   README.md		tests	     utils
env.sh	    log       requirements.txt	third_party


In [14]:
print(np.testing.assert_equal(torch_mask, encoder_mask.numpy()))

None


In [15]:
print(np.allclose(torch_encoder_out, encoder_out.numpy()))
print(torch_encoder_out[0])

False
[[-0.70815086  0.5656927   0.709813   ...  1.0982457   0.7758755
   1.1307045 ]
 [-0.78350693  0.39481696  0.74499094 ...  1.2273936   0.8813775
   1.3142622 ]
 [-0.9625825   0.63913065  0.90481734 ...  0.9587627   0.73829174
   1.2868171 ]
 ...
 [-1.089918    0.6853822   0.9498568  ...  0.8842667   0.81529033
   1.325533  ]
 [-1.1811031   0.6971649   0.7225241  ...  1.200684    0.8006199
   1.4533575 ]
 [-1.2878689   0.72914284  0.7896784  ...  0.916238    0.87275296
   1.2629912 ]]


In [33]:
from paddle.nn import functional as F
def ctc_loss(logits,
             labels,
             input_lengths,
             label_lengths,
             blank=0,
             reduction='mean',
             norm_by_times=False):
    loss_out = paddle.fluid.layers.warpctc(logits, labels, blank, norm_by_times,
                                           input_lengths, label_lengths)
    loss_out = paddle.fluid.layers.squeeze(loss_out, [-1])
    assert reduction in ['mean', 'sum', 'none']
    if reduction == 'mean':
        loss_out = paddle.mean(loss_out / label_lengths)
    elif reduction == 'sum':
        loss_out = paddle.sum(loss_out)
    return loss_out

F.ctc_loss = ctc_loss

torch_mask_t = paddle.to_tensor(torch_mask, dtype='int64')
encoder_out_lens = torch_mask_t.squeeze(1).sum(1)
loss_ctc = model.ctc(paddle.to_tensor(torch_encoder_out), encoder_out_lens, text, text_len)
print(loss_ctc)
# ctc tensor(377.2479, device='cuda:0', grad_fn=<DivBackward0>)
loss_ctc.backward()
print(loss_ctc.grad)
print(model.ctc.ctc_lo.weight.grad)
print(model.ctc.ctc_lo.bias.grad)
# tensor([[ 3.2806e+00, -1.8297e+00, -2.5472e+00,  ..., -4.4421e+00,
#          -3.4516e+00, -6.8526e+00],
#         [-1.5462e-02,  8.0163e-03,  1.3837e-02,  ...,  2.4541e-02,
#           1.7295e-02,  3.5211e-02],
#         [ 5.0349e-02, -4.5908e-02, -2.8797e-02,  ..., -8.8659e-02,
#          -6.3412e-02, -1.2411e-01],
#         ...,
#         [-2.4901e-03,  1.0179e-03,  2.3745e-03,  ...,  4.3330e-03,
#           3.2267e-03,  6.2963e-03],
#         [-6.0131e-03,  2.5570e-03,  6.0628e-03,  ...,  1.1443e-02,
#           8.4951e-03,  1.6021e-02],
#         [-7.2826e-03,  2.3929e-03,  7.7757e-03,  ...,  1.4101e-02,
#           1.0566e-02,  2.0105e-02]], device='cuda:0')

Tensor(shape=[16, 51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[-0.70815086,  0.56569272,  0.70981300, ...,  1.09824574,  0.77587551,  1.13070452],
         [-0.78350693,  0.39481696,  0.74499094, ...,  1.22739363,  0.88137752,  1.31426215],
         [-0.96258253,  0.63913065,  0.90481734, ...,  0.95876271,  0.73829174,  1.28681707],
         ...,
         [-1.08991802,  0.68538219,  0.94985682, ...,  0.88426667,  0.81529033,  1.32553303],
         [-1.18110311,  0.69716489,  0.72252411, ...,  1.20068395,  0.80061990,  1.45335746],
         [-1.28786886,  0.72914284,  0.78967839, ...,  0.91623801,  0.87275296,  1.26299119]],

        [[-0.92869806,  0.66449726,  0.50940996, ...,  0.67377377,  0.75721473,  1.44601321],
         [-0.58323175,  0.39969942,  0.46701184, ...,  0.76123071,  0.82149148,  1.53387356],
         [-0.66912395,  0.42107889,  0.53314692, ...,  0.77352434,  0.73588967,  1.55955291],
         ...,
         [-0.91979462,  0.78827965,  0.51

In [17]:
loss_att, acc_att = model._calc_att_loss(paddle.to_tensor(torch_encoder_out), paddle.to_tensor(torch_mask),
                                                    text, text_len)
print(loss_att, acc_att)
#tensor(41.8416, device='cuda:0', grad_fn=<DivBackward0>) 0.0

Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [36.31002045]) 0.0


In [18]:
# encoder, decoder + att_loss 不对齐

In [20]:
data = np.load(".notebook/decoder.npz", allow_pickle=True)
torch_decoder_out = data['decoder_out']

In [47]:
def add_sos_eos(ys_pad: paddle.Tensor, sos: int, eos: int,
                ignore_id: int):
    """Add <sos> and <eos> labels.
    Args:
        ys_pad (paddle.Tensor): batch of padded target sequences (B, Lmax)
        sos (int): index of <sos>
        eos (int): index of <eeos>
        ignore_id (int): index of padding
    Returns:
        ys_in (paddle.Tensor) : (B, Lmax + 1)
        ys_out (paddle.Tensor) : (B, Lmax + 1)
    Examples:
        >>> sos_id = 10
        >>> eos_id = 11
        >>> ignore_id = -1
        >>> ys_pad
        tensor([[ 1,  2,  3,  4,  5],
                [ 4,  5,  6, -1, -1],
                [ 7,  8,  9, -1, -1]], dtype=paddle.int32)
        >>> ys_in,ys_out=add_sos_eos(ys_pad, sos_id , eos_id, ignore_id)
        >>> ys_in
        tensor([[10,  1,  2,  3,  4,  5],
                [10,  4,  5,  6, 11, 11],
                [10,  7,  8,  9, 11, 11]])
        >>> ys_out
        tensor([[ 1,  2,  3,  4,  5, 11],
                [ 4,  5,  6, 11, -1, -1],
                [ 7,  8,  9, 11, -1, -1]])
    """
    # TODO(Hui Zhang): using comment code, 
    #_sos = paddle.to_tensor(
    #    [sos], dtype=paddle.long, stop_gradient=True, place=ys_pad.place)
    #_eos = paddle.to_tensor(
    #    [eos], dtype=paddle.long, stop_gradient=True, place=ys_pad.place)
    #ys = [y[y != ignore_id] for y in ys_pad]  # parse padded ys
    #ys_in = [paddle.cat([_sos, y], dim=0) for y in ys]
    #ys_out = [paddle.cat([y, _eos], dim=0) for y in ys]
    #return pad_sequence(ys_in, padding_value=eos), pad_sequence(ys_out, padding_value=ignore_id)
    B = ys_pad.size(0)
    _sos = paddle.ones([B, 1], dtype=ys_pad.dtype) * sos
    _eos = paddle.ones([B, 1], dtype=ys_pad.dtype) * eos
    ys_in = paddle.cat([_sos, ys_pad], dim=1)
    mask_pad = (ys_in == ignore_id)
    ys_in = ys_in.masked_fill(mask_pad, eos)
    

    ys_out = paddle.cat([ys_pad, _eos], dim=1)
    ys_out = ys_out.masked_fill(mask_pad, eos)
    mask_eos = (ys_out == ignore_id)
    ys_out = ys_out.masked_fill(mask_eos, eos)
    ys_out = ys_out.masked_fill(mask_pad, ignore_id)
    return ys_in, ys_out

In [48]:
ys_pad = text
ys_pad_lens = text_len
ys_in_pad, ys_out_pad = add_sos_eos(ys_pad, model.sos, model.eos,
                                model.ignore_id)
ys_in_lens = ys_pad_lens + 1
print(ys_in_pad)
print(ys_out_pad)

Tensor(shape=[16, 7], dtype=int32, place=CUDAPlace(0), stop_gradient=True,
       [[4232, 2995, 3116, 1209, 565 , 4232, 4232],
        [4232, 236 , 1176, 331 , 66  , 3925, 4077],
        [4232, 2693, 524 , 234 , 1145, 366 , 4232],
        [4232, 3875, 4211, 3062, 700 , 4232, 4232],
        [4232, 272 , 987 , 1134, 494 , 2959, 4232],
        [4232, 1936, 3715, 120 , 2553, 2695, 2710],
        [4232, 25  , 1149, 3930, 4232, 4232, 4232],
        [4232, 1753, 1778, 1237, 482 , 3925, 110 ],
        [4232, 3703, 2   , 565 , 3827, 4232, 4232],
        [4232, 1150, 2734, 10  , 2478, 3490, 4232],
        [4232, 426 , 811 , 95  , 489 , 144 , 4232],
        [4232, 2313, 2006, 489 , 975 , 4232, 4232],
        [4232, 3702, 3414, 205 , 1488, 2966, 1347],
        [4232, 70  , 1741, 702 , 1666, 4232, 4232],
        [4232, 703 , 1778, 1030, 849 , 4232, 4232],
        [4232, 814 , 1674, 115 , 3827, 4232, 4232]])
Tensor(shape=[16, 7], dtype=int32, place=CUDAPlace(0), stop_gradient=True,
       [[2995, 31

In [49]:
decoder_out, _ = model.decoder(encoder_out, encoder_mask, ys_in_pad,
                                      ys_in_lens)
print(decoder_out.shape)
print(decoder_out[0])
print(np.allclose(decoder_out.numpy(), torch_decoder_out))

[16, 7, 4233]
Tensor(shape=[7, 4233], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[-0.37553221, -0.83114165,  0.70238966, ...,  0.30866742,  0.03037567,  0.43291825],
        [-0.87047130, -0.32394654,  0.37882078, ...,  0.34444264, -0.12801090, -0.97179270],
        [-0.43517584,  0.02496703, -0.32672805, ...,  0.04601809, -1.15214014, -0.23627253],
        ...,
        [ 0.42706215,  0.58341736, -0.01791662, ...,  0.34311637,  0.06014483, -0.34610766],
        [-0.37887222, -0.81906295,  0.71680295, ...,  0.22679621,  0.01455487,  0.45493346],
        [-0.38187075, -0.82030386,  0.70901453, ...,  0.22812662,  0.01431785,  0.45638454]])
False


In [50]:
loss_att = model.criterion_att(paddle.to_tensor(torch_decoder_out), ys_out_pad)
print(loss_att)
print(ys_out_pad)
# tensor(41.8416, device='cuda:0', grad_fn=<DivBackward0>)

Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [41.84283447])
Tensor(shape=[16, 7], dtype=int32, place=CUDAPlace(0), stop_gradient=True,
       [[2995, 3116, 1209,  565, 4232, -1  , -1  ],
        [ 236, 1176,  331,  66 , 3925, 4077, 4232],
        [2693,  524,  234, 1145,  366, 4232, -1  ],
        [3875, 4211, 3062,  700, 4232, -1  , -1  ],
        [ 272,  987, 1134,  494, 2959, 4232, -1  ],
        [1936, 3715,  120, 2553, 2695, 2710, 4232],
        [ 25 , 1149, 3930, 4232, -1  , -1  , -1  ],
        [1753, 1778, 1237,  482, 3925,  110, 4232],
        [3703,  2  ,  565, 3827, 4232, -1  , -1  ],
        [1150, 2734,  10 , 2478, 3490, 4232, -1  ],
        [ 426,  811,  95 ,  489,  144, 4232, -1  ],
        [2313, 2006,  489,  975, 4232, -1  , -1  ],
        [3702, 3414,  205, 1488, 2966, 1347, 4232],
        [ 70 , 1741,  702, 1666, 4232, -1  , -1  ],
        [ 703, 1778, 1030,  849, 4232, -1  , -1  ],
        [ 814, 1674,  115, 3827, 4232, -1  , -1  ]

In [52]:
decoder_out, _ = model.decoder(encoder_out, encoder_mask, ys_in_pad,
                                      ys_in_lens)
loss_att = model.criterion_att(paddle.to_tensor(torch_decoder_out), ys_out_pad)

None
