In [1]:
%cd ..
%pwd

/workspace/DeepSpeech-2.x


'/workspace/DeepSpeech-2.x'

In [2]:
import numpy as np
import paddle
from yacs.config import CfgNode as CN

from deepspeech.models.u2 import U2Model
from deepspeech.utils.layer_tools import print_params
from deepspeech.utils.layer_tools import summary

/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
register user softmax to paddle, remove this when fixed!
register user log_softmax to paddle, remove this when fixed!
register user sigmoid to paddle, remove this when fixed!
register user log_sigmoid to paddle, remove this when fixed!
register user relu to paddle, remove this when fixed!
override cat of paddle if exists or register, remove this when fixe

In [3]:
conf_str='examples/aishell/s1/conf/conformer.yaml'
cfg = CN().load_cfg(open(conf_str))
cfg.model.input_dim = 80
cfg.model.output_dim = 4233
cfg.model.cmvn_file = "/workspace/wenet/examples/aishell/s0/raw_wav/train/global_cmvn"
cfg.model.cmvn_file_type = 'json'
cfg.freeze()

model = U2Model(cfg.model)
print_params(model)


/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
[INFO 2021/04/19 06:57:01 u2.py:834] U2 Encoder type: conformer


encoder.embed.conv.0.weight | [256, 1, 3, 3] | 2304 | True
encoder.embed.conv.0.bias | [256] | 256 | True
encoder.embed.conv.2.weight | [256, 256, 3, 3] | 589824 | True
encoder.embed.conv.2.bias | [256] | 256 | True
encoder.embed.out.0.weight | [4864, 256] | 1245184 | True
encoder.embed.out.0.bias | [256] | 256 | True
encoder.after_norm.weight | [256] | 256 | True
encoder.after_norm.bias | [256] | 256 | True
encoder.encoders.0.self_attn.pos_bias_u | [4, 64] | 256 | True
encoder.encoders.0.self_attn.pos_bias_v | [4, 64] | 256 | True
encoder.encoders.0.self_attn.linear_q.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_q.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_k.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_k.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_v.weight | [256, 256] | 65536 | True
encoder.encoders.0.self_attn.linear_v.bias | [256] | 256 | True
encoder.encoders.0.self_attn.linear_out.weight | [2

In [4]:
summary(model)

encoder.global_cmvn.mean | [80] | 80
encoder.global_cmvn.istd | [80] | 80
encoder.embed.conv.0.weight | [256, 1, 3, 3] | 2304
encoder.embed.conv.0.bias | [256] | 256
encoder.embed.conv.2.weight | [256, 256, 3, 3] | 589824
encoder.embed.conv.2.bias | [256] | 256
encoder.embed.out.0.weight | [4864, 256] | 1245184
encoder.embed.out.0.bias | [256] | 256
encoder.after_norm.weight | [256] | 256
encoder.after_norm.bias | [256] | 256
encoder.encoders.0.self_attn.pos_bias_u | [4, 64] | 256
encoder.encoders.0.self_attn.pos_bias_v | [4, 64] | 256
encoder.encoders.0.self_attn.linear_q.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_q.bias | [256] | 256
encoder.encoders.0.self_attn.linear_k.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_k.bias | [256] | 256
encoder.encoders.0.self_attn.linear_v.weight | [256, 256] | 65536
encoder.encoders.0.self_attn.linear_v.bias | [256] | 256
encoder.encoders.0.self_attn.linear_out.weight | [256, 256] | 65536
encoder.encoders.0.se

decoder.decoders.3.norm2.weight | [256] | 256
decoder.decoders.3.norm2.bias | [256] | 256
decoder.decoders.3.norm3.weight | [256] | 256
decoder.decoders.3.norm3.bias | [256] | 256
decoder.decoders.3.concat_linear1.weight | [512, 256] | 131072
decoder.decoders.3.concat_linear1.bias | [256] | 256
decoder.decoders.3.concat_linear2.weight | [512, 256] | 131072
decoder.decoders.3.concat_linear2.bias | [256] | 256
decoder.decoders.4.self_attn.linear_q.weight | [256, 256] | 65536
decoder.decoders.4.self_attn.linear_q.bias | [256] | 256
decoder.decoders.4.self_attn.linear_k.weight | [256, 256] | 65536
decoder.decoders.4.self_attn.linear_k.bias | [256] | 256
decoder.decoders.4.self_attn.linear_v.weight | [256, 256] | 65536
decoder.decoders.4.self_attn.linear_v.bias | [256] | 256
decoder.decoders.4.self_attn.linear_out.weight | [256, 256] | 65536
decoder.decoders.4.self_attn.linear_out.bias | [256] | 256
decoder.decoders.4.src_attn.linear_q.weight | [256, 256] | 65536
decoder.decoders.4.src_attn

In [6]:
print(model)

U2Model(
  (encoder): ConformerEncoder(
    (global_cmvn): GlobalCMVN()
    (embed): Conv2dSubsampling4(
      (pos_enc): RelPositionalEncoding(
        (dropout): Dropout(p=0.1, axis=None, mode=upscale_in_train)
      )
      (conv): Sequential(
        (0): Conv2D(1, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (1): ReLU()
        (2): Conv2D(256, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (3): ReLU()
      )
      (out): Sequential(
        (0): Linear(in_features=4864, out_features=256, dtype=float32)
      )
    )
    (after_norm): LayerNorm(normalized_shape=[256], epsilon=1e-12)
    (encoders): LayerList(
      (0): ConformerEncoderLayer(
        (self_attn): RelPositionMultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, dtype=float32)
          (linear_k): Linear(in_features=256, out_features=256, dtype=float32)
          (linear_v): Linear(in_features=256, out_features=256, dtype=float32)
          (l

In [7]:
%ls .notebook

compute_cmvn_loader_test.ipynb         jit_infer.ipynb
dataloader.ipynb                       mask_and_masked_fill_test.ipynb
dataloader_with_tokens_tokenids.ipynb  model.npz
data.npz                               python_test.ipynb
decoder.npz                            train_test.ipynb
encoder.npz                            u2_model.ipynb
hack_api_test.ipynb


In [8]:
data = np.load('.notebook/data.npz', allow_pickle=True)
keys=data['keys']
feat=data['feat']
feat_len=data['feat_len']
text=data['text']
text_len=data['text_len']

In [9]:
print(keys)
print(feat.shape)
print(feat)
print(feat_len)
print(text)
print(text_len)

['BAC009S0739W0246' 'BAC009S0727W0424' 'BAC009S0753W0412'
 'BAC009S0756W0206' 'BAC009S0740W0414' 'BAC009S0728W0426'
 'BAC009S0739W0214' 'BAC009S0753W0423' 'BAC009S0734W0201'
 'BAC009S0740W0427' 'BAC009S0730W0423' 'BAC009S0728W0367'
 'BAC009S0730W0418' 'BAC009S0727W0157' 'BAC009S0749W0409'
 'BAC009S0727W0418']
(16, 207, 80)
[[[ 8.994624   9.538309   9.191589  ... 10.507416   9.563305   8.256403 ]
  [ 9.798841  10.405224   9.26511   ... 10.251211   9.543982   8.873768 ]
  [10.6890745 10.395469   8.053548  ...  9.906749  10.064903   8.050915 ]
  ...
  [ 9.217986   9.65069    8.505259  ...  9.687183   8.742463   7.9865475]
  [10.129122   9.935194   9.37982   ...  9.563894   9.825992   8.979543 ]
  [ 9.095531   7.1338377  9.468001  ...  9.472748   9.021235   7.447914 ]]

 [[11.430976  10.671858   6.0841026 ...  9.382682   8.729745   7.5315614]
  [ 9.731717   7.8104815  7.5714607 ... 10.043035   9.243595   7.3540792]
  [10.65017   10.600604   8.467784  ...  9.281448   9.186885   8.070343 ]
 

In [10]:
# ['BAC009S0739W0246', 'BAC009S0727W0424', 'BAC009S0753W0412', 'BAC009S0756W0206', 'BAC009S0740W0414', 'BAC009S0728W0426', 'BAC009S0739W0214', 'BAC009S0753W0423', 'BAC009S0734W0201', 'BAC009S0740W0427', 'BAC009S0730W0423', 'BAC009S0728W0367', 'BAC009S0730W0418', 'BAC009S0727W0157', 'BAC009S0749W0409', 'BAC009S0727W0418']
# torch.Size([16, 207, 80])
# tensor([[[ 8.9946,  9.5383,  9.1916,  ..., 10.5074,  9.5633,  8.2564],
#          [ 9.7988, 10.4052,  9.2651,  ..., 10.2512,  9.5440,  8.8738],
#          [10.6891, 10.3955,  8.0535,  ...,  9.9067, 10.0649,  8.0509],
#          ...,
#          [ 9.2180,  9.6507,  8.5053,  ...,  9.6872,  8.7425,  7.9865],
#          [10.1291,  9.9352,  9.3798,  ...,  9.5639,  9.8260,  8.9795],
#          [ 9.0955,  7.1338,  9.4680,  ...,  9.4727,  9.0212,  7.4479]],

#         [[11.4310, 10.6719,  6.0841,  ...,  9.3827,  8.7297,  7.5316],
#          [ 9.7317,  7.8105,  7.5715,  ..., 10.0430,  9.2436,  7.3541],
#          [10.6502, 10.6006,  8.4678,  ...,  9.2814,  9.1869,  8.0703],
#          ...,
#          [ 9.0970,  9.2637,  8.0753,  ...,  8.4318,  8.3705,  8.0029],
#          [10.4617, 10.1478,  6.7693,  ...,  9.7794,  9.5775,  8.0807],
#          [ 7.7944,  5.6211,  7.9751,  ...,  9.9972,  9.8497,  8.0313]],

#         [[ 7.3456,  7.8964,  7.5796,  ..., 11.6310, 10.4513,  9.1236],
#          [ 8.6287,  8.4631,  7.4992,  ..., 12.4160, 10.9757,  8.9426],
#          [ 9.8314, 10.2813,  8.9724,  ..., 12.1387, 10.4017,  9.0055],
#          ...,
#          [ 7.0896,  7.4055,  6.8143,  ...,  9.3252,  9.2732,  8.3534],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         ...,

#         [[10.9332, 10.4644,  7.7203,  ..., 10.3488,  9.3023,  7.1553],
#          [10.4499,  9.9070,  9.0293,  ...,  9.9525,  9.4141,  7.5593],
#          [10.4877,  9.8126,  9.8952,  ...,  9.5866,  9.3413,  7.7849],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         [[ 9.9444,  9.5859,  8.2203,  ..., 11.5886, 11.0450,  8.8171],
#          [ 7.6784,  8.3224,  7.5330,  ..., 11.0551, 10.5357,  9.2746],
#          [ 8.6262,  9.6759,  9.8410,  ..., 11.3788, 10.9221,  8.9914],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

#         [[ 8.1079,  7.7590,  6.7103,  ..., 12.6506, 11.4662, 11.0615],
#          [11.3803, 11.2220,  8.6589,  ..., 12.8106, 12.2222, 11.6893],
#          [10.6777,  9.9206,  8.0461,  ..., 13.5729, 12.5624, 11.1550],
#          ...,
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
#          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]])
# tensor([207, 207, 205, 205, 203, 203, 198, 197, 195, 188, 186, 186, 185, 180,
#         166, 163], dtype=torch.int32)
# tensor([[2995, 3116, 1209,  565,   -1,   -1],
#         [ 236, 1176,  331,   66, 3925, 4077],
#         [2693,  524,  234, 1145,  366,   -1],
#         [3875, 4211, 3062,  700,   -1,   -1],
#         [ 272,  987, 1134,  494, 2959,   -1],
#         [1936, 3715,  120, 2553, 2695, 2710],
#         [  25, 1149, 3930,   -1,   -1,   -1],
#         [1753, 1778, 1237,  482, 3925,  110],
#         [3703,    2,  565, 3827,   -1,   -1],
#         [1150, 2734,   10, 2478, 3490,   -1],
#         [ 426,  811,   95,  489,  144,   -1],
#         [2313, 2006,  489,  975,   -1,   -1],
#         [3702, 3414,  205, 1488, 2966, 1347],
#         [  70, 1741,  702, 1666,   -1,   -1],
#         [ 703, 1778, 1030,  849,   -1,   -1],
#         [ 814, 1674,  115, 3827,   -1,   -1]], dtype=torch.int32)
# tensor([4, 6, 5, 4, 5, 6, 3, 6, 4, 5, 5, 4, 6, 4, 4, 4], dtype=torch.int32)

In [12]:
!ls .notebook
data = np.load('.notebook/model.npz', allow_pickle=True)
state_dict = data['state'].item()

for key, _ in model.state_dict().items():
    if key not in state_dict:
        print(f"{key} not find.")

model.set_state_dict(state_dict)

now_state_dict = model.state_dict()
for key, value in now_state_dict.items():
    if not np.allclose(value.numpy(), state_dict[key]):
        print(key)

compute_cmvn_loader_test.ipynb	       jit_infer.ipynb
dataloader.ipynb		       mask_and_masked_fill_test.ipynb
dataloader_with_tokens_tokenids.ipynb  model.npz
data.npz			       python_test.ipynb
decoder.npz			       train_test.ipynb
encoder.npz			       u2_model.ipynb
hack_api_test.ipynb


In [13]:
import paddle
feat=paddle.to_tensor(feat)
feat_len=paddle.to_tensor(feat_len, dtype='int64')
text=paddle.to_tensor(text, dtype='int64')
text_len=paddle.to_tensor(text_len, dtype='int64')

model.eval()
total_loss, attention_loss, ctc_loss = model(feat, feat_len,
                                         text, text_len)
print(total_loss, attention_loss, ctc_loss )

/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:687: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:


Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [142.48880005]) Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [41.84146118]) Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [377.33258057])


/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:238: UserWarning: The dtype of left and right variables are not the same, left dtype is VarType.FP32, but right dtype is VarType.INT32, the right dtype will convert to VarType.FP32
  format(lhs_dtype, rhs_dtype, lhs_dtype))


In [11]:
# tensor(142.4858, device='cuda:0', grad_fn=<AddBackward0>) tensor(41.8416, device='cuda:0', grad_fn=<DivBackward0>) tensor(377.3222, device='cuda:0', grad_fn=<DivBackward0>)

In [14]:
encoder_out, encoder_mask = model.encoder(feat, feat_len)
print(encoder_out.shape)
print(encoder_mask.shape)
print(encoder_out[0])


[16, 51, 256]
[16, 1, 51]
Tensor(shape=[51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[-0.70194179,  0.56254166,  0.68803459, ...,  1.12373221,  0.78039235,  1.13693869],
        [-0.77877808,  0.39126658,  0.71887815, ...,  1.25188220,  0.88616788,  1.31734526],
        [-0.95908946,  0.63460249,  0.87671334, ...,  0.98183727,  0.74401081,  1.29032660],
        ...,
        [-1.07322502,  0.67236906,  0.92303109, ...,  0.90754563,  0.81767166,  1.32396567],
        [-1.16541159,  0.68199694,  0.69394493, ...,  1.22383487,  0.80282891,  1.45065081],
        [-1.27320945,  0.71458030,  0.75819558, ...,  0.94154912,  0.87748396,  1.26230514]])


In [15]:
!ls
data = np.load('.notebook/encoder.npz', allow_pickle=True)
torch_mask = data['mask']
torch_encoder_out = data['out']

deepspeech  examples  README_cn.md	setup.sh     tools
docs	    LICENSE   README.md		tests	     utils
env.sh	    log       requirements.txt	third_party


In [16]:
print(np.testing.assert_equal(torch_mask, encoder_mask.numpy()))

None


In [17]:
print(np.allclose(torch_encoder_out, encoder_out.numpy()))
print(torch_encoder_out[0])

False
[[-0.7019424   0.56254166  0.6880345  ...  1.1237322   0.78039217
   1.1369387 ]
 [-0.778778    0.39126638  0.7188779  ...  1.2518823   0.8861681
   1.3173454 ]
 [-0.9590891   0.6346026   0.87671363 ...  0.9818373   0.74401116
   1.2903274 ]
 ...
 [-1.0732253   0.6723689   0.9230311  ...  0.9075457   0.8176713
   1.3239657 ]
 [-1.165412    0.6819976   0.69394535 ...  1.2238353   0.80282927
   1.4506509 ]
 [-1.2732087   0.71458083  0.7581961  ...  0.9415482   0.877484
   1.2623053 ]]


In [18]:
from paddle.nn import functional as F
def ctc_loss(logits,
             labels,
             input_lengths,
             label_lengths,
             blank=0,
             reduction='mean',
             norm_by_times=False):
    loss_out = paddle.fluid.layers.warpctc(logits, labels, blank, norm_by_times,
                                           input_lengths, label_lengths)
    loss_out = paddle.fluid.layers.squeeze(loss_out, [-1])
    assert reduction in ['mean', 'sum', 'none']
    if reduction == 'mean':
        loss_out = paddle.mean(loss_out / label_lengths)
    elif reduction == 'sum':
        loss_out = paddle.sum(loss_out)
    return loss_out

F.ctc_loss = ctc_loss

torch_mask_t = paddle.to_tensor(torch_mask, dtype='int64')
encoder_out_lens = torch_mask_t.squeeze(1).sum(1)
loss_ctc = model.ctc(paddle.to_tensor(torch_encoder_out), encoder_out_lens, text, text_len)
print(loss_ctc)
loss_ctc.backward()
print(loss_ctc.grad)
print(model.ctc.ctc_lo.weight.grad)
print(model.ctc.ctc_lo.bias.grad)
# tensor(377.3222, device='cuda:0', grad_fn=<DivBackward0>)
# None
# tensor([[ 3.1708e+00, -1.7475e+00, -2.3708e+00,  ..., -4.4351e+00,
#          -3.3900e+00, -6.6965e+00],
#         [-1.5185e-02,  7.7655e-03,  1.3137e-02,  ...,  2.4917e-02,
#           1.7287e-02,  3.5098e-02],
#         [ 4.9522e-02, -4.5104e-02, -2.6280e-02,  ..., -9.0381e-02,
#          -6.3512e-02, -1.2436e-01],
#         ...,
#         [-2.4678e-03,  9.8464e-04,  2.2739e-03,  ...,  4.4535e-03,
#           3.2612e-03,  6.3516e-03],
#         [-5.9237e-03,  2.4569e-03,  5.7726e-03,  ...,  1.1697e-02,
#           8.5412e-03,  1.6078e-02],
#         [-7.2193e-03,  2.2864e-03,  7.4629e-03,  ...,  1.4516e-02,
#           1.0693e-02,  2.0319e-02]], device='cuda:0')
# tensor([-4.4342e+00,  2.3348e-02, -9.3497e-02,  ...,  4.2513e-03,
#          1.0928e-02,  1.3751e-02], device='cuda:0')

Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [377.32220459])
[1.]
[[ 3.1708076e+00 -1.5184805e-02  4.9524564e-02 ... -2.4678309e-03
  -5.9236852e-03 -7.2192554e-03]
 [-1.7474542e+00  7.7654729e-03 -4.5106117e-02 ...  9.8463835e-04
   2.4569160e-03  2.2863639e-03]
 [-2.3707268e+00  1.3136451e-02 -2.6281785e-02 ...  2.2738585e-03
   5.7726162e-03  7.4628354e-03]
 ...
 [-4.4350743e+00  2.4916438e-02 -9.0385124e-02 ...  4.4534383e-03
   1.1696636e-02  1.4515720e-02]
 [-3.3899918e+00  1.7287316e-02 -6.3514955e-02 ...  3.2612216e-03
   8.5411733e-03  1.0692922e-02]
 [-6.6964636e+00  3.5097409e-02 -1.2437013e-01 ...  6.3515711e-03
   1.6078018e-02  2.0318989e-02]]
[-4.4341431e+00  2.3347888e-02 -9.3501516e-02 ...  4.2512305e-03
  1.0928102e-02  1.3750527e-02]


In [19]:
loss_att, acc_att = model._calc_att_loss(paddle.to_tensor(torch_encoder_out), paddle.to_tensor(torch_mask),
                                                    text, text_len)
print(loss_att, acc_att)
#tensor(41.8416, device='cuda:0', grad_fn=<DivBackward0>) 0.0

Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [41.84160995]) 0.0


In [20]:
# encoder, decoder不对齐

In [21]:
data = np.load(".notebook/decoder.npz", allow_pickle=True)
torch_decoder_out = data['decoder_out']
print(torch_decoder_out[0])

[[-3.7638968e-01 -8.2272053e-01  7.4276292e-01 ...  3.4200522e-01
   1.5034772e-02  4.0337229e-01]
 [-8.7386459e-01 -3.1389427e-01  4.1987866e-01 ...  3.7723729e-01
  -1.4352810e-01 -1.0023664e+00]
 [-4.3505096e-01  3.4504786e-02 -2.8710306e-01 ...  7.7274129e-02
  -1.1672243e+00 -2.6848501e-01]
 ...
 [ 4.2471480e-01  5.8885634e-01  2.0203922e-02 ...  3.7405500e-01
   4.5470044e-02 -3.7139410e-01]
 [-3.7978446e-01 -8.1084180e-01  7.5725085e-01 ...  2.6038891e-01
  -7.9347193e-04  4.2537671e-01]
 [-3.8279903e-01 -8.1206715e-01  7.4943429e-01 ...  2.6173013e-01
  -1.0499060e-03  4.2678756e-01]]


In [22]:
def add_sos_eos(ys_pad: paddle.Tensor, sos: int, eos: int,
                ignore_id: int):
    """Add <sos> and <eos> labels.
    Args:
        ys_pad (paddle.Tensor): batch of padded target sequences (B, Lmax)
        sos (int): index of <sos>
        eos (int): index of <eeos>
        ignore_id (int): index of padding
    Returns:
        ys_in (paddle.Tensor) : (B, Lmax + 1)
        ys_out (paddle.Tensor) : (B, Lmax + 1)
    Examples:
        >>> sos_id = 10
        >>> eos_id = 11
        >>> ignore_id = -1
        >>> ys_pad
        tensor([[ 1,  2,  3,  4,  5],
                [ 4,  5,  6, -1, -1],
                [ 7,  8,  9, -1, -1]], dtype=paddle.int32)
        >>> ys_in,ys_out=add_sos_eos(ys_pad, sos_id , eos_id, ignore_id)
        >>> ys_in
        tensor([[10,  1,  2,  3,  4,  5],
                [10,  4,  5,  6, 11, 11],
                [10,  7,  8,  9, 11, 11]])
        >>> ys_out
        tensor([[ 1,  2,  3,  4,  5, 11],
                [ 4,  5,  6, 11, -1, -1],
                [ 7,  8,  9, 11, -1, -1]])
    """
    # TODO(Hui Zhang): using comment code, 
    #_sos = paddle.to_tensor(
    #    [sos], dtype=paddle.long, stop_gradient=True, place=ys_pad.place)
    #_eos = paddle.to_tensor(
    #    [eos], dtype=paddle.long, stop_gradient=True, place=ys_pad.place)
    #ys = [y[y != ignore_id] for y in ys_pad]  # parse padded ys
    #ys_in = [paddle.cat([_sos, y], dim=0) for y in ys]
    #ys_out = [paddle.cat([y, _eos], dim=0) for y in ys]
    #return pad_sequence(ys_in, padding_value=eos), pad_sequence(ys_out, padding_value=ignore_id)
    B = ys_pad.size(0)
    _sos = paddle.ones([B, 1], dtype=ys_pad.dtype) * sos
    _eos = paddle.ones([B, 1], dtype=ys_pad.dtype) * eos
    ys_in = paddle.cat([_sos, ys_pad], dim=1)
    mask_pad = (ys_in == ignore_id)
    ys_in = ys_in.masked_fill(mask_pad, eos)
    

    ys_out = paddle.cat([ys_pad, _eos], dim=1)
    ys_out = ys_out.masked_fill(mask_pad, eos)
    mask_eos = (ys_out == ignore_id)
    ys_out = ys_out.masked_fill(mask_eos, eos)
    ys_out = ys_out.masked_fill(mask_pad, ignore_id)
    return ys_in, ys_out

In [23]:
ys_pad = text
ys_pad_lens = text_len
ys_in_pad, ys_out_pad = add_sos_eos(ys_pad, model.sos, model.eos,
                                model.ignore_id)
ys_in_lens = ys_pad_lens + 1
print(ys_in_pad)
print(ys_out_pad)

Tensor(shape=[16, 7], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[4232, 2995, 3116, 1209, 565 , 4232, 4232],
        [4232, 236 , 1176, 331 , 66  , 3925, 4077],
        [4232, 2693, 524 , 234 , 1145, 366 , 4232],
        [4232, 3875, 4211, 3062, 700 , 4232, 4232],
        [4232, 272 , 987 , 1134, 494 , 2959, 4232],
        [4232, 1936, 3715, 120 , 2553, 2695, 2710],
        [4232, 25  , 1149, 3930, 4232, 4232, 4232],
        [4232, 1753, 1778, 1237, 482 , 3925, 110 ],
        [4232, 3703, 2   , 565 , 3827, 4232, 4232],
        [4232, 1150, 2734, 10  , 2478, 3490, 4232],
        [4232, 426 , 811 , 95  , 489 , 144 , 4232],
        [4232, 2313, 2006, 489 , 975 , 4232, 4232],
        [4232, 3702, 3414, 205 , 1488, 2966, 1347],
        [4232, 70  , 1741, 702 , 1666, 4232, 4232],
        [4232, 703 , 1778, 1030, 849 , 4232, 4232],
        [4232, 814 , 1674, 115 , 3827, 4232, 4232]])
Tensor(shape=[16, 7], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[2995, 31

In [24]:
decoder_out, _ = model.decoder(encoder_out, encoder_mask, ys_in_pad,
                                      ys_in_lens)
print(decoder_out.shape)
print(decoder_out[0])
print(np.allclose(decoder_out.numpy(), torch_decoder_out))

[16, 7, 4233]
Tensor(shape=[7, 4233], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[-0.37638962, -0.82272029,  0.74276292, ...,  0.34200522,  0.01503509,  0.40337229],
        [-0.87386417, -0.31389427,  0.41987872, ...,  0.37723723, -0.14352795, -1.00236630],
        [-0.43505096,  0.03450463, -0.28710306, ...,  0.07727426, -1.16722453, -0.26848495],
        ...,
        [ 0.42471474,  0.58885634,  0.02020410, ...,  0.37405482,  0.04546990, -0.37139422],
        [-0.37978464, -0.81084198,  0.75725073, ...,  0.26038912, -0.00079346,  0.42537683],
        [-0.38279879, -0.81206709,  0.74943423, ...,  0.26172996, -0.00104988,  0.42678767]])
False


In [25]:
from paddle import nn
import paddle
class LabelSmoothingLoss(nn.Layer):

    def __init__(self,
                 size: int,
                 padding_idx: int,
                 smoothing: float,
                 normalize_length: bool=False):
        super().__init__()
        self.size = size
        self.padding_idx = padding_idx
        self.smoothing = smoothing
        self.confidence = 1.0 - smoothing
        self.normalize_length = normalize_length
        self.criterion = nn.KLDivLoss(reduction="none")

    def forward(self, x: paddle.Tensor, target: paddle.Tensor) -> paddle.Tensor:
        """Compute loss between x and target.
        The model outputs and data labels tensors are flatten to
        (batch*seqlen, class) shape and a mask is applied to the
        padding part which should not be calculated for loss.
        
        Args:
            x (paddle.Tensor): prediction (batch, seqlen, class)
            target (paddle.Tensor):
                target signal masked with self.padding_id (batch, seqlen)
        Returns:
            loss (paddle.Tensor) : The KL loss, scalar float value
        """
        B, T, D = paddle.shape(x)
        assert D == self.size
        x = x.reshape((-1, self.size))
        target = target.reshape([-1])

        # use zeros_like instead of torch.no_grad() for true_dist,
        # since no_grad() can not be exported by JIT
        true_dist = paddle.full_like(x, self.smoothing / (self.size - 1))
        ignore = target == self.padding_idx  # (B,)
        print(self.smoothing / (self.size - 1))
        print(true_dist)

        #target = target * (1 - ignore)  # avoid -1 index
        target = target.masked_fill(ignore, 0)  # avoid -1 index
        
        
        #true_dist += F.one_hot(target, self.size) * self.confidence
        target_mask = F.one_hot(target, self.size)
        true_dist *= (1 - target_mask)
        true_dist += target_mask * self.confidence
        

        kl = self.criterion(F.log_softmax(x, axis=1), true_dist)
        
        #TODO(Hui Zhang): sum not support bool type
        #total = len(target) - int(ignore.sum())
        total = len(target) - int(ignore.type_as(target).sum())
        denom = total if self.normalize_length else B

        #numer = (kl * (1 - ignore)).sum()
        numer = kl.masked_fill(ignore.unsqueeze(1), 0).sum()
        return numer / denom


In [26]:
criteron = LabelSmoothingLoss(4233, -1, 0.1, False)
loss_att = criteron(paddle.to_tensor(torch_decoder_out), ys_out_pad.astype('int64'))
print(loss_att)
print(ys_out_pad.dtype)
# tensor(41.8416, device='cuda:0', grad_fn=<DivBackward0>)

2.3629489603024576e-05
Tensor(shape=[112, 4233], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363],
        [0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363],
        [0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363],
        ...,
        [0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363],
        [0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363],
        [0.00002363, 0.00002363, 0.00002363, ..., 0.00002363, 0.00002363, 0.00002363]])
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [41.84160995])
VarType.INT64


In [27]:
decoder_out, _ = model.decoder(encoder_out, encoder_mask, ys_in_pad,
                                      ys_in_lens)

loss_att = model.criterion_att(paddle.to_tensor(torch_decoder_out), ys_out_pad)
print(loss_att)

loss_att = model.criterion_att(decoder_out, ys_out_pad)
print(loss_att)

print(model.criterion_att.size)
print(model.criterion_att.padding_idx)
print(model.criterion_att.smoothing)
print(model.criterion_att.normalize_length)

Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [41.84160995])
Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [41.84146118])
4233
-1
0.1
False


In [28]:
from typing import List
from typing import Optional
from typing import Tuple

import paddle
from paddle import nn
from typeguard import check_argument_types

from deepspeech.modules.activation import get_activation
from deepspeech.modules.attention import MultiHeadedAttention
from deepspeech.modules.attention import RelPositionMultiHeadedAttention
from deepspeech.modules.conformer_convolution import ConvolutionModule
from deepspeech.modules.embedding import PositionalEncoding
from deepspeech.modules.embedding import RelPositionalEncoding
from deepspeech.modules.encoder_layer import ConformerEncoderLayer
from deepspeech.modules.encoder_layer import TransformerEncoderLayer
from deepspeech.modules.mask import add_optional_chunk_mask
from deepspeech.modules.mask import make_non_pad_mask
from deepspeech.modules.positionwise_feed_forward import PositionwiseFeedForward
from deepspeech.modules.subsampling import Conv2dSubsampling4
from deepspeech.modules.subsampling import Conv2dSubsampling6
from deepspeech.modules.subsampling import Conv2dSubsampling8
from deepspeech.modules.subsampling import LinearNoSubsampling

class BaseEncoder(nn.Layer):
    def __init__(
            self,
            input_size: int,
            output_size: int=256,
            attention_heads: int=4,
            linear_units: int=2048,
            num_blocks: int=6,
            dropout_rate: float=0.1,
            positional_dropout_rate: float=0.1,
            attention_dropout_rate: float=0.0,
            input_layer: str="conv2d",
            pos_enc_layer_type: str="abs_pos",
            normalize_before: bool=True,
            concat_after: bool=False,
            static_chunk_size: int=0,
            use_dynamic_chunk: bool=False,
            global_cmvn: paddle.nn.Layer=None,
            use_dynamic_left_chunk: bool=False, ):
        """
        Args:
            input_size (int): input dim, d_feature
            output_size (int): dimension of attention, d_model
            attention_heads (int): the number of heads of multi head attention
            linear_units (int): the hidden units number of position-wise feed
                forward
            num_blocks (int): the number of encoder blocks
            dropout_rate (float): dropout rate
            attention_dropout_rate (float): dropout rate in attention
            positional_dropout_rate (float): dropout rate after adding
                positional encoding
            input_layer (str): input layer type.
                optional [linear, conv2d, conv2d6, conv2d8]
            pos_enc_layer_type (str): Encoder positional encoding layer type.
                opitonal [abs_pos, scaled_abs_pos, rel_pos]
            normalize_before (bool):
                True: use layer_norm before each sub-block of a layer.
                False: use layer_norm after each sub-block of a layer.
            concat_after (bool): whether to concat attention layer's input
                and output.
                True: x -> x + linear(concat(x, att(x)))
                False: x -> x + att(x)
            static_chunk_size (int): chunk size for static chunk training and
                decoding
            use_dynamic_chunk (bool): whether use dynamic chunk size for
                training or not, You can only use fixed chunk(chunk_size > 0)
                or dyanmic chunk size(use_dynamic_chunk = True)
            global_cmvn (Optional[paddle.nn.Layer]): Optional GlobalCMVN layer
            use_dynamic_left_chunk (bool): whether use dynamic left chunk in
                dynamic chunk training
        """
        assert check_argument_types()
        super().__init__()
        self._output_size = output_size

        if pos_enc_layer_type == "abs_pos":
            pos_enc_class = PositionalEncoding
        elif pos_enc_layer_type == "rel_pos":
            pos_enc_class = RelPositionalEncoding
        else:
            raise ValueError("unknown pos_enc_layer: " + pos_enc_layer_type)

        if input_layer == "linear":
            subsampling_class = LinearNoSubsampling
        elif input_layer == "conv2d":
            subsampling_class = Conv2dSubsampling4
        elif input_layer == "conv2d6":
            subsampling_class = Conv2dSubsampling6
        elif input_layer == "conv2d8":
            subsampling_class = Conv2dSubsampling8
        else:
            raise ValueError("unknown input_layer: " + input_layer)

        self.global_cmvn = global_cmvn
        self.embed = subsampling_class(
            idim=input_size,
            odim=output_size,
            dropout_rate=dropout_rate,
            pos_enc_class=pos_enc_class(
                d_model=output_size, dropout_rate=positional_dropout_rate), )

        self.normalize_before = normalize_before
        self.after_norm = nn.LayerNorm(output_size, epsilon=1e-12)
        self.static_chunk_size = static_chunk_size
        self.use_dynamic_chunk = use_dynamic_chunk
        self.use_dynamic_left_chunk = use_dynamic_left_chunk

    def output_size(self) -> int:
        return self._output_size

    def forward(
            self,
            xs: paddle.Tensor,
            xs_lens: paddle.Tensor,
            decoding_chunk_size: int=0,
            num_decoding_left_chunks: int=-1,
    ) -> Tuple[paddle.Tensor, paddle.Tensor]:
        """Embed positions in tensor.
        Args:
            xs: padded input tensor (B, L, D)
            xs_lens: input length (B)
            decoding_chunk_size: decoding chunk size for dynamic chunk
                0: default for training, use random dynamic chunk.
                <0: for decoding, use full chunk.
                >0: for decoding, use fixed chunk size as set.
            num_decoding_left_chunks: number of left chunks, this is for decoding,
                the chunk size is decoding_chunk_size.
                >=0: use num_decoding_left_chunks
                <0: use all left chunks
        Returns:
            encoder output tensor, lens and mask
        """
        masks = make_non_pad_mask(xs_lens).unsqueeze(1)  # (B, 1, L)

        if self.global_cmvn is not None:
            xs = self.global_cmvn(xs)
        #TODO(Hui Zhang): self.embed(xs, masks, offset=0), stride_slice not support bool tensor
        xs, pos_emb, masks = self.embed(xs, masks.type_as(xs), offset=0)
        #TODO(Hui Zhang): remove mask.astype, stride_slice not support bool tensor
        masks = masks.astype(paddle.bool)
        #TODO(Hui Zhang): mask_pad = ~masks
        mask_pad = masks.logical_not()
        chunk_masks = add_optional_chunk_mask(
            xs, masks, self.use_dynamic_chunk, self.use_dynamic_left_chunk,
            decoding_chunk_size, self.static_chunk_size,
            num_decoding_left_chunks)
        for layer in self.encoders:
            xs, chunk_masks, _ = layer(xs, chunk_masks, pos_emb, mask_pad)
        if self.normalize_before:
            xs = self.after_norm(xs)
        # Here we assume the mask is not changed in encoder layers, so just
        # return the masks before encoder layers, and the masks will be used
        # for cross attention with decoder later
        return xs, masks

In [29]:

class ConformerEncoder(BaseEncoder):
    """Conformer encoder module."""

    def __init__(
            self,
            input_size: int,
            output_size: int=256,
            attention_heads: int=4,
            linear_units: int=2048,
            num_blocks: int=6,
            dropout_rate: float=0.1,
            positional_dropout_rate: float=0.1,
            attention_dropout_rate: float=0.0,
            input_layer: str="conv2d",
            pos_enc_layer_type: str="rel_pos",
            normalize_before: bool=True,
            concat_after: bool=False,
            static_chunk_size: int=0,
            use_dynamic_chunk: bool=False,
            global_cmvn: nn.Layer=None,
            use_dynamic_left_chunk: bool=False,
            positionwise_conv_kernel_size: int=1,
            macaron_style: bool=True,
            selfattention_layer_type: str="rel_selfattn",
            activation_type: str="swish",
            use_cnn_module: bool=True,
            cnn_module_kernel: int=15,
            causal: bool=False,
            cnn_module_norm: str="batch_norm", ):
        """Construct ConformerEncoder
        Args:
            input_size to use_dynamic_chunk, see in BaseEncoder
            positionwise_conv_kernel_size (int): Kernel size of positionwise
                conv1d layer.
            macaron_style (bool): Whether to use macaron style for
                positionwise layer.
            selfattention_layer_type (str): Encoder attention layer type,
                the parameter has no effect now, it's just for configure
                compatibility.
            activation_type (str): Encoder activation function type.
            use_cnn_module (bool): Whether to use convolution module.
            cnn_module_kernel (int): Kernel size of convolution module.
            causal (bool): whether to use causal convolution or not.
            cnn_module_norm (str): cnn conv norm type, Optional['batch_norm','layer_norm']
        """
        assert check_argument_types()
        super().__init__(input_size, output_size, attention_heads, linear_units,
                         num_blocks, dropout_rate, positional_dropout_rate,
                         attention_dropout_rate, input_layer,
                         pos_enc_layer_type, normalize_before, concat_after,
                         static_chunk_size, use_dynamic_chunk, global_cmvn,
                         use_dynamic_left_chunk)
        activation = get_activation(activation_type)

        # self-attention module definition
        encoder_selfattn_layer = RelPositionMultiHeadedAttention
        encoder_selfattn_layer_args = (attention_heads, output_size,
                                       attention_dropout_rate)
        # feed-forward module definition
        positionwise_layer = PositionwiseFeedForward
        positionwise_layer_args = (output_size, linear_units, dropout_rate,
                                   activation)
        # convolution module definition
        convolution_layer = ConvolutionModule
        convolution_layer_args = (output_size, cnn_module_kernel, activation,
                                  cnn_module_norm, causal)

        self.encoders = nn.ModuleList([
            ConformerEncoderLayer(
                size=output_size,
                self_attn=encoder_selfattn_layer(*encoder_selfattn_layer_args),
                feed_forward=positionwise_layer(*positionwise_layer_args),
                feed_forward_macaron=positionwise_layer(
                    *positionwise_layer_args) if macaron_style else None,
                conv_module=convolution_layer(*convolution_layer_args)
                if use_cnn_module else None,
                dropout_rate=dropout_rate,
                normalize_before=normalize_before,
                concat_after=concat_after) for _ in range(num_blocks)
        ])


In [30]:
from deepspeech.frontend.utility import load_cmvn
from deepspeech.modules.cmvn import GlobalCMVN

configs=cfg.model
mean, istd = load_cmvn(configs['cmvn_file'],
                               configs['cmvn_file_type'])
global_cmvn = GlobalCMVN(
    paddle.to_tensor(mean, dtype=paddle.float),
    paddle.to_tensor(istd, dtype=paddle.float))


input_dim = configs['input_dim']
vocab_size = configs['output_dim']
encoder_type = configs.get('encoder', 'transformer')
        
encoder = ConformerEncoder(
                input_dim, global_cmvn=global_cmvn, **configs['encoder_conf'])

In [31]:
o = global_cmvn(feat)
o2 = model.encoder.global_cmvn(feat)
print(np.allclose(o.numpy(), o2.numpy()))

True


In [32]:
from deepspeech.modules.mask import make_non_pad_mask
from deepspeech.modules.mask import make_pad_mask
masks = make_non_pad_mask(feat_len).unsqueeze(1)
print(masks)

Tensor(shape=[16, 1, 207], dtype=bool, place=CUDAPlace(0), stop_gradient=True,
       [[[True , True , True , ..., True , True , True ]],

        [[True , True , True , ..., True , True , True ]],

        [[True , True , True , ..., True , False, False]],

        ...,

        [[True , True , True , ..., False, False, False]],

        [[True , True , True , ..., False, False, False]],

        [[True , True , True , ..., False, False, False]]])


In [33]:
xs = model.encoder.global_cmvn(feat)
print(xs)

Tensor(shape=[16, 207, 80], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[-0.53697914, -0.19910523, -0.34997201, ..., -0.82427669, -1.02650309, -0.96300691],
         [-0.04464225,  0.23176001, -0.32538742, ..., -0.90158713, -1.03248465, -0.75986791],
         [ 0.50035292,  0.22691160, -0.73052198, ..., -1.00552964, -0.87123060, -1.03062117],
         ...,
         [-0.40023831, -0.14325078, -0.57947433, ..., -1.07178426, -1.28059900, -1.05180073],
         [ 0.15755332, -0.00184949, -0.28702953, ..., -1.10898709, -0.94518697, -0.72506356],
         [-0.47520429, -1.39415145, -0.25754252, ..., -1.13649082, -1.19430351, -1.22903371]],

        [[ 0.95454037,  0.36427975, -1.38908529, ..., -1.16366839, -1.28453600, -1.20151031],
         [-0.08573537, -1.05785275, -0.89172721, ..., -0.96440506, -1.12547100, -1.25990939],
         [ 0.47653601,  0.32886592, -0.59200549, ..., -1.19421589, -1.14302588, -1.02422845],
         ...,
         [-0.47431335, -0.33558893, -0.72

In [34]:
xs = model.encoder.global_cmvn(feat)
masks = make_non_pad_mask(feat_len).unsqueeze(1)


#xs, pos_emb, masks = model.encoder.embed(xs, masks.type_as(xs), offset=0)
# print(xs)

x = xs.unsqueeze(1)
x = model.encoder.embed.conv(x)
print(x)

Tensor(shape=[16, 256, 51, 19], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[[0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          ...,
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ]],

         [[0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.00209083],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        ],
          ...,
          [0.        , 0.01194306, 0.        , ..., 0.        , 0.        , 0. 

In [36]:
b, c, t, f = paddle.shape(x)
x = model.encoder.embed.out(x.transpose([0, 2, 1, 3]).reshape([b, t, c * f]))
print(x)
x, pos_emb = model.encoder.embed.pos_enc(x, 0)
print(x)

Tensor(shape=[16, 51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[-0.03426375,  0.14291267, -0.06718873, ...,  0.09064753,  0.01809387, -0.04340880],
         [-0.05007839,  0.11054724, -0.10399298, ...,  0.11457238,  0.04244684, -0.01249714],
         [-0.10695291,  0.16910909, -0.08352133, ...,  0.07710276,  0.01168563, -0.03584499],
         ...,
         [-0.06060536,  0.14455931, -0.05470302, ...,  0.05364908,  0.03033342, -0.02610814],
         [-0.08505894,  0.13611752, -0.11132983, ...,  0.13079923,  0.01580139, -0.02281028],
         [-0.10604677,  0.14714901, -0.10885533, ...,  0.08543444,  0.03719445, -0.04634233]],

        [[-0.12392755,  0.14486063, -0.05674079, ...,  0.02573164,  0.03128851,  0.00545091],
         [-0.04775286,  0.08473608, -0.08507854, ...,  0.04573154,  0.04240163,  0.01053247],
         [-0.05940291,  0.10023535, -0.08143730, ...,  0.03596500,  0.01673085,  0.02089563],
         ...,
         [-0.09222981,  0.15823206, -0.0

In [37]:
xs = model.encoder.global_cmvn(feat)
masks = make_non_pad_mask(feat_len).unsqueeze(1)

xs, pos_emb, masks = model.encoder.embed(xs, masks.type_as(xs), offset=0)
print(xs)

Tensor(shape=[16, 51, 256], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[-0.54821998,  2.28660274, -1.07501972, ...,  1.45036042,  0.28950194, -0.69454080],
         [-0.80125421,  1.76875579, -1.66388774, ...,  1.83315802,  0.67914939, -0.19995420],
         [-1.71124649,  2.70574546, -1.33634126, ...,  1.23364413,  0.18697014, -0.57351983],
         ...,
         [-0.96968573,  2.31294894, -0.87524825, ...,  0.85838526,  0.48533469, -0.41773027],
         [-1.36094308,  2.17788029, -1.78127730, ...,  2.09278774,  0.25282228, -0.36496443],
         [-1.69674826,  2.35438418, -1.74168527, ...,  1.36695099,  0.59511113, -0.74147725]],

        [[-1.98284078,  2.31777000, -0.90785271, ...,  0.41170627,  0.50061619,  0.08721463],
         [-0.76404583,  1.35577726, -1.36125672, ...,  0.73170459,  0.67842603,  0.16851945],
         [-0.95044655,  1.60376561, -1.30299675, ...,  0.57544005,  0.26769355,  0.33433008],
         ...,
         [-1.47567701,  2.53171301, -1.2

In [43]:
encoder_out, encoder_mask = model.encoder(feat, feat_len)
print(encoder_out.shape)
print(encoder_mask.shape)
print(encoder_out[0])
print(torch_encoder_out[0])

SystemError: (Fatal) Operator elementwise_sub raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1.010986MB memory on GPU 0, available memory is only 6.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
. (at /paddle/paddle/fluid/imperative/tracer.cc:172)
